import {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  HeadingLevel, AlignmentType, BorderStyle, WidthType, ShadingType,
  Header, Footer,
} from 'docx';
import type { PlanRecord } from './types';
import { TIER_LABELS, LANGUAGE_LABELS } from './constants';

const IDSS_BLUE   = '002D6E';
const IDSS_GOLD   = 'F0B429';
const IDSS_LIGHT  = 'EBF0F8';
const MONO_FONT   = 'Courier New';
const BODY_FONT   = 'Calibri';

export async function generateDocx(plan: PlanRecord): Promise<Buffer> {
  const langKey = plan.language === 'bosnian' ? 'bs'
                : plan.language === 'german'  ? 'de'
                : 'en';

  const tierLabel = TIER_LABELS[plan.tier][langKey];

  const doc = new Document({
    creator:     'IBL Planer v2.0 — IDSS',
    title:       `IBL Plan: ${plan.subject} ${plan.grade}. razred — ${plan.topic}`,
    description: `Generated by IBL Lesson Plan Creator. PSI v8.0.`,

    styles: {
      default: {
        document: {
          run: { font: BODY_FONT, size: 22 },
        },
      },
    },

    sections: [{
      properties: {
        page: {
          margin: { top: 1134, bottom: 1134, left: 1134, right: 1134 },
        },
      },

      headers: {
        default: new Header({
          children: [
            new Table({
              width: { size: 100, type: WidthType.PERCENTAGE },
              borders: {
                top:    { style: BorderStyle.NONE },
                bottom: { style: BorderStyle.SINGLE, size: 6, color: IDSS_GOLD },
                left:   { style: BorderStyle.NONE },
                right:  { style: BorderStyle.NONE },
              },
              rows: [new TableRow({
                children: [
                  new TableCell({
                    width: { size: 70, type: WidthType.PERCENTAGE },
                    borders: { top: { style: BorderStyle.NONE }, bottom: { style: BorderStyle.NONE }, left: { style: BorderStyle.NONE }, right: { style: BorderStyle.NONE } },
                    children: [new Paragraph({
                      children: [
                        new TextRun({ text: 'PLANER ZA IBL LEKCIJU', bold: true, color: IDSS_BLUE, size: 20, font: BODY_FONT }),
                        new TextRun({ text: '\nInternationale Deutsche Schule Sarajevo', color: '555555', size: 16, font: BODY_FONT, break: 1 }),
                      ],
                    })],
                  }),
                  new TableCell({
                    width: { size: 30, type: WidthType.PERCENTAGE },
                    borders: { top: { style: BorderStyle.NONE }, bottom: { style: BorderStyle.NONE }, left: { style: BorderStyle.NONE }, right: { style: BorderStyle.NONE } },
                    children: [new Paragraph({
                      alignment: AlignmentType.RIGHT,
                      children: [
                        new TextRun({ text: `PSI v8.0 · ${tierLabel}`, color: '888888', size: 14, font: BODY_FONT }),
                      ],
                    })],
                  }),
                ],
              })],
            }),
          ],
        }),
      },

      footers: {
        default: new Footer({
          children: [new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({ text: 'IBL Planer v2.0  ·  Internationale Deutsche Schule Sarajevo  ·  majaljubovic@gmail.com', size: 16, color: '888888', font: BODY_FONT }),
            ],
          })],
        }),
      },

      children: [
        // ── METADATA TABLE ──────────────────────────────────
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          borders: {
            top:    { style: BorderStyle.SINGLE, size: 4, color: IDSS_BLUE },
            bottom: { style: BorderStyle.SINGLE, size: 4, color: IDSS_BLUE },
            left:   { style: BorderStyle.SINGLE, size: 4, color: IDSS_BLUE },
            right:  { style: BorderStyle.SINGLE, size: 4, color: IDSS_BLUE },
          },
          rows: [
            metaRow('Škola',     'Internationale Deutsche Schule Sarajevo'),
            metaRow('Nastavnik', '___________________________________'),
            metaRow('Predmet',   `${plan.subject}  |  ${plan.grade}. razred`),
            metaRow('Tema',      plan.topic),
            metaRow('Trajanje',  `${plan.duration_min} min  |  ${tierLabel}`),
            metaRow('Jezik',     LANGUAGE_LABELS[plan.language]),
            metaRow('Datum',     new Date(plan.created_at).toLocaleDateString('de-DE')),
          ],
        }),

        spacer(),

        // ── INQUIRY QUESTION CALLOUT ─────────────────────────
        ...(plan.inquiry_question ? [
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            borders: {
              top:    { style: BorderStyle.NONE },
              bottom: { style: BorderStyle.NONE },
              left:   { style: BorderStyle.SINGLE, size: 12, color: IDSS_GOLD },
              right:  { style: BorderStyle.NONE },
            },
            rows: [new TableRow({
              children: [new TableCell({
                shading: { type: ShadingType.CLEAR, fill: 'FFFBF0' },
                margins: { left: 200, right: 200, top: 100, bottom: 100 },
                borders: { top: { style: BorderStyle.NONE }, bottom: { style: BorderStyle.NONE }, left: { style: BorderStyle.NONE }, right: { style: BorderStyle.NONE } },
                children: [
                  new Paragraph({
                    children: [new TextRun({ text: '❓ ISTRAŽIVAČKO PITANJE', bold: true, color: IDSS_BLUE, size: 18, font: BODY_FONT })],
                  }),
                  new Paragraph({
                    children: [new TextRun({ text: plan.inquiry_question, italics: true, size: 22, font: BODY_FONT })],
                  }),
                ],
              })],
            })],
          }),
          spacer(),
        ] : []),

        // ── PLAN TEXT (monospace) ────────────────────────────
        new Paragraph({
          children: [new TextRun({ text: 'KOMPLETAN PLAN ČASA', bold: true, color: IDSS_BLUE, size: 24, font: BODY_FONT })],
          spacing: { before: 200, after: 100 },
        }),

        ...plan.plan_text.split('\n').map(line =>
          new Paragraph({
            children: [new TextRun({ text: line || ' ', font: MONO_FONT, size: 18 })],
            spacing: { before: 0, after: 0, line: 240 },
          })
        ),

        spacer(),

        // ── GENERATION METADATA ───────────────────────────────
        new Paragraph({
          children: [
            new TextRun({ text: `Generisano: ${new Date(plan.created_at).toLocaleString('de-DE')}`, size: 16, color: '999999', font: BODY_FONT }),
            new TextRun({ text: `   |   Trajanje generisanja: ${((plan.generation_time_ms ?? 0) / 1000).toFixed(1)}s`, size: 16, color: '999999', font: BODY_FONT }),
          ],
        }),
      ],
    }],
  });

  const buffer = await Packer.toBuffer(doc);
  return buffer;
}

// ── helpers ────────────────────────────────────────────────────────────────

function metaRow(label: string, value: string): TableRow {
  return new TableRow({
    children: [
      new TableCell({
        width: { size: 25, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.CLEAR, fill: IDSS_LIGHT },
        margins: { left: 100, right: 100, top: 60, bottom: 60 },
        children: [new Paragraph({
          children: [new TextRun({ text: label, bold: true, size: 18, font: BODY_FONT, color: IDSS_BLUE })],
        })],
      }),
      new TableCell({
        width: { size: 75, type: WidthType.PERCENTAGE },
        margins: { left: 100, right: 100, top: 60, bottom: 60 },
        children: [new Paragraph({
          children: [new TextRun({ text: value, size: 18, font: BODY_FONT })],
        })],
      }),
    ],
  });
}

function spacer(): Paragraph {
  return new Paragraph({ children: [new TextRun({ text: '' })], spacing: { before: 160, after: 160 } });
}